package com.aaak.euler.problem.twelve;

/**
 * Project Euler Problem 12: Highly Divisible Triangular Number
 *
 * Problem:
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *   1: 1
 *   3: 1,3
 *   6: 1,2,3,6
 *  10: 1,2,5,10
 *  15: 1,3,5,15
 *  21: 1,3,7,21
 *  28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * Approach:
 * 1. Generate triangle numbers sequentially using T(n) = n * (n + 1) / 2
 * 2. For each triangle number, count its divisors efficiently by iterating only up to sqrt(n)
 * 3. Return the first triangle number that has more than 500 divisors
 *
 * Optimization:
 * - Divisor counting is optimized to O(sqrt(n)) by counting pairs of divisors
 * - For each divisor i where i * i <= n, we count both i and n/i (unless they're equal)
 *
 * Expected answer: 76576500
 */
public class HighlyDivisibleTriangularNumber {

    private static final int DIVISOR_THRESHOLD = 500;

    public static void main(String[] args) {
        long start = System.currentTimeMillis();

        long result = findFirstTriangleNumberWithDivisorsOver(DIVISOR_THRESHOLD);

        System.out.println("The first triangle number with over " + DIVISOR_THRESHOLD + " divisors is: " + result);
        System.out.println("Number of divisors: " + countDivisors(result));
        System.out.println("Time taken: " + (System.currentTimeMillis() - start) + " ms");
    }

    /**
     * Finds the first triangle number with more than the specified number of divisors.
     *
     * @param threshold The minimum number of divisors (exclusive)
     * @return The first triangle number with more than threshold divisors
     */
    public static long findFirstTriangleNumberWithDivisorsOver(int threshold) {
        long n = 1;
        long triangleNumber = 0;

        while (true) {
            triangleNumber += n;  // T(n) = T(n-1) + n
            int divisorCount = countDivisors(triangleNumber);

            if (divisorCount > threshold) {
                return triangleNumber;
            }
            n++;
        }
    }

    /**
     * Counts the number of divisors of a given number efficiently.
     * Uses the property that divisors come in pairs (d, n/d) where d <= sqrt(n).
     *
     * @param n The number to count divisors for
     * @return The total number of divisors
     */
    public static int countDivisors(long n) {
        if (n <= 0) {
            return 0;
        }

        int count = 0;
        long sqrt = (long) Math.sqrt(n);

        for (long i = 1; i <= sqrt; i++) {
            if (n % i == 0) {
                if (i * i == n) {
                    // Perfect square: count only once
                    count++;
                } else {
                    // Count both i and n/i
                    count += 2;
                }
            }
        }

        return count;
    }
}
